serverless-operations/serverless-step-functions

- index.js
> fix typo (invoke's description was for remove's)

- lib/index.js
> Non-zero exit status when fail

- README.md
https://github.com/horike37/serverless-step-functions/commit/ff684f18a3ecbc2ae683d43ac1aebc95c23127be
> Be README adapted to commit: ff684f1.  `state' options is obsoleted.

- README.md
- lib/deploy/stepFunctions/compileIamRole.js
Addressing #59 
fixes  `functions/lib/deploy/stepFunctions/compileIamRole.js` file substituting
\- `iamRoleStateMachineExecutionTemplate.replace('[region]', this.region)
`
\+ `iamRoleStateMachineExecutionTemplate.replace('[region]', this.options.region)
`
All tests passed:
`
Coverage summary
Statements   : 100% ( 334/334 )
Branches     : 100% ( 106/106 )
Functions    : 100% ( 42/42 )
Lines        : 100% ( 331/331 )
`
Cheers!
> Invalid principal smrole fix

- README.md
> Update README.md - spelling 

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
* Removed some characters in https://github.com/horike37/serverless-step-functions/pull/147 from the regex that I thought weren't valid but they are. So just adding those back.
> Allow pseudo-parameters in function arn regex

- README.md
- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.test.js
- lib/index.js
- lib/index.test.js
Implements the suggestion from #163
> add support for specifying CloudWatch Alarms

- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
> support global tags

- README.md
- lib/deploy/events/schedule/compileScheduledEvents.js
- lib/deploy/events/schedule/compileScheduledEvents.test.js
Implementation of solution for #128
> feat: allow the specification of a custom IAM role for scheduled events

- README.md
I found this documentation link helpful and thought it would be useful in the README: https://github.com/horike37/serverless-step-functions/issues/162#issuecomment-462987698
> Add API Gateway request mapping template docs link

- README.md
- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
Closes #162
Example JSON payload:
```
{
"body": {
"x": 42,
"y": 20
},
"httpMethod": "POST",
"path": "/dev/yan/ada",
"resource": "/{userId}/{petId}",
"headers": {
"Accept": "*/*",
"Accept-Encoding": "gzip, deflate",
"cache-control": "no-cache",
"CloudFront-Forwarded-Proto": "https",
"CloudFront-Is-Desktop-Viewer": "true",
"CloudFront-Is-Mobile-Viewer": "false",
"CloudFront-Is-SmartTV-Viewer": "false",
"CloudFront-Is-Tablet-Viewer": "false",
"CloudFront-Viewer-Country": "GB",
"Content-Type": "application/json",
"Host": "w7kv6bolzh.execute-api.us-east-1.amazonaws.com",
"Postman-Token": "596fe5f1-c826-4878-87b4-e931a50171ca",
"User-Agent": "PostmanRuntime/7.1.1",
"Via": "1.1 8d36edc1ce736c158ddedbd7365e2a8e.cloudfront.net (CloudFront)",
"X-Amz-Cf-Id": …
```
> feature: support lambda_proxy req template

- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/utils/aws.js
> fix: handle null values

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Closes #201
Generate correct IAM permissions for callbacks
> feat: support callbacks

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> feat: support lambda:invoke resource type

- README.md
- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
> feat: add support for AuthorizationScopes

- README.md
- lib/deploy/events/apiGateway/iamRole.js
- lib/deploy/events/apiGateway/iamRole.test.js
- lib/deploy/events/apiGateway/methods.js
> feat: support iamRole override for HTTP events

- lib/deploy/events/apiGateway/validate.js
- lib/deploy/events/apiGateway/validate.test.js
> fix: scopes is now passed through validation

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> Support intrinsic functions in lambda:invoke resource type

- lib/deploy/events/apiGateway/lambdaPermissions.js
- lib/deploy/events/apiGateway/lambdaPermissions.test.js
- lib/index.js
- lib/index.test.js
Closes #152
Generate the associated Lambda permission resources for authorizers.
> feat: generate LambdaPermission for authorizers

- package-lock.json
- package.json
Fixed security alerts which has been shown on github.
https://github.com/horike37/serverless-step-functions/network/alerts
> Fix security alerts

- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.schema.js
- lib/deploy/stepFunctions/compileAlarms.test.js
> feat: support override for alarm logical id

- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
Follow up PR of #141 Closes #140
Thanks to @marcelalburg for the initial work done and to @lendesk-pawel-cisek for his advise on how to test it.
> Fix VTL simple quote escaping

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> feat: add support for nested workflows

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> feat: support the new Map state

- package-lock.json
- package.json
new version of asl-validator added support for Map
Closes #257
> build: updated asl-validator

- lib/deploy/stepFunctions/compileStateMachines.schema.js
> feat: support Fn::ImportValue

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/naming.js
- lib/naming.test.js
> feat: one IAM role per state machine

- lib/deploy/events/apiGateway/deployment.js
- lib/deploy/events/apiGateway/deployment.test.js
> fix: "undefined" in API GW deployment's logical id

- README.md
- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.schema.js
- lib/deploy/stepFunctions/compileAlarms.test.js
> fix: incorrect alarm time for ExecutionsTimedOut

- README.md
> Add section about loggingConfig for standard workflows

- README.md
Sorry, forgot this small detail.
> docs: add missing entry in TOC list

- package-lock.json
- package.json
Addresses ticket #347 
Should this be a `feat`?
> fix: #347 Remove aws-sdk dependency

- lib/deploy/stepFunctions/compileStateMachines.js
- package-lock.json
- package.json
Leverage https://github.com/airware/asl-validator/pull/46 feature to show humanized version of errors to user (instead of raw JSON).
Depends on https://github.com/airware/asl-validator/pull/46
Fixes #310
> feat:  human readable errors in state schema validation

- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
> fix: handle empty tag values

- lib/deploy/events/apiGateway/apiKeys.test.js
- lib/deploy/events/apiGateway/cors.test.js
- lib/deploy/events/apiGateway/deployment.test.js
- lib/deploy/events/apiGateway/endpointInfo.test.js
- lib/deploy/events/apiGateway/iamRole.test.js
- lib/deploy/events/apiGateway/lambdaPermissions.test.js
- lib/deploy/events/apiGateway/methods.test.js
- lib/deploy/events/apiGateway/resources.test.js
- lib/deploy/events/apiGateway/restApi.test.js
- lib/deploy/events/apiGateway/usagePlan.test.js
- lib/deploy/events/apiGateway/usagePlanKeys.test.js
- lib/deploy/events/apiGateway/validate.test.js
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.test.js
- lib/deploy/events/schedule/compileScheduledEvents.test.js
- lib/deploy/stepFunctions/compileActivities.test.js
- lib/deploy/stepFunctions/compileAlarms.test.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/deploy/stepFunctions/compileNotifications.test.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/index.test.js
- lib/invoke/invoke.test.js
- lib/naming.test.js
- lib/yamlParser.test.js
Fixing tests after the merge of #357
> chore: fixed tests

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- Add CodeBuild and EventBridge permissions required for codebuild Tasks
> feat(codebuild): add IAM policy statement generation for codebuild

- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.schema.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
Related issue: #373
Added `tracingConfig` property.
> feat: X-Ray tracing support for state machine

- README.md
Update `Version` based on this [doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html).
> doc: update PolicyDocument version

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> feat: add put events policy if eventbridge task is used by machine

- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
> fix: handles issue when Ref value is passed to Seconds for Wait task

- README.md
- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> feat: support importing DynamoDB tables exported from external stacks

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Hi, I have created this PR regarding issue #482
> fix: generate IAM roles when using AWS SDK integration with DynamoDB

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/iam-role-statemachine-execution-template.txt
- lib/naming.js
- lib/naming.test.js
This PR changes the role template to use the pseudo region parameter.
fixes #407
> feat: use pseudo region in role template

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Hi, i've create a pr for this issue https://github.com/serverless-operations/serverless-step-functions/issues/497
> feat: dynamodb update table iam policy

- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.js
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.test.js
Hi, I added this change which closes #503. Included test cases and followed how schedule events work. Also tested deploying my stack and referencing a role with GetAtt. Thanks!
> feat: allow setting intrinsic functions for CW Events iamRole

- lib/deploy/events/apiGateway/restApi.js
- lib/deploy/events/apiGateway/restApi.test.js
Fixes: https://github.com/serverless-operations/serverless-step-functions/issues/523
> add vpcEndpointIds to EndpointConfiguration

- package-lock.json
Reverts serverless-operations/serverless-step-functions#559
> Revert "chore(deps): bump xml2js and aws-sdk"

- package-lock.json
- package.json
Current validator do not validate Distributed Map correctly
> chore: upgrade sl-validator for distributed maop

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
I encountered a permissions issue when trying to loop through files in a bucket within a stepfunctions map.
The following PR solves the problem.
Feel free to improve or correct it.
Thanks for your great work
> Ad support to s3:listObjectsV2

- .github/workflows/config.yml
- package-lock.json
- package.json
Add https://github.com/stackblitz-labs/pkg.pr.new for previewing PRs
> build: add pkg.pr.new previews
