- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/naming.js
- lib/naming.test.js
- package.json
Allow users to provide their own stepMachine naming convention.
_example_ 
```
functions:
hello:
handler: handler.hello
stepFunctions:
stateMachines:
hellostepfunc:
Name: hellostepfunc-${opt:stage}
definition:
<your definition>
plugins:
- serverless-step-functions
```
> Custom naming for serverless-step-functions

- README.md
If you copy the formatting of the README it results in an error `Cannot read property 'path' of null`. This fixed it for me.
> Not indenting path and method results in error

- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/index.js
- lib/index.test.js
- lib/invoke/invoke.js
- lib/invoke/invoke.test.js
- lib/yamlParser.js
- package-lock.json
This PR updates functionality for the [new update feature](https://aws.amazon.com/about-aws/whats-new/2017/11/aws-step-functions-adds-support-for-updating-state-machines/) in CloudFormation for Step Function's state machines. It resolves [Issue #87](https://github.com/horike37/serverless-step-functions/issues/87).
You can pass in an optional name and the CloudFormation stack will pass that name to the new `StateMachineName` field on the `AWS::StepFunctions::StateMachine` type. More info [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html). If no optional name is passed, it defaults to the same conventions as before.
I tweaked the unit tests a little to make it all work. I then tested deployments with a name passed and no name …
> add support for new update state machine feature

- lib/yamlParser.test.js
I'm studying AWS Step Functions and found this plugin. When I executed $ npm test I realized there was a missing branch test.
Basically I included happy-case tests to make instanbul happy
```js
=============================== Coverage summary ===============================
Statements   : 100% ( 469/469 )
Branches     : 100% ( 200/200 )
Functions    : 100% ( 51/51 )
Lines        : 100% ( 466/466 )
```
> Improve branch code coverage

- lib/index.js
- lib/index.test.js
Display nothing instead of:
```
Serverless StepFunctions OutPuts
endpoints:
```
Because that information is useless if user never configured endpoints.
> Do not display endpoints if there are none

- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
Adding `private:true` to state machine events
```
"events": [
{
"http": {
"path": "delijn/bookings/callback",
"method": "post",
"private": true
}
}
]
```
Should set `ApiKeyRequired: true` in `AWS::ApiGateway::Method` template.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-setup-api-key-with-restapi.html
Without this parameter x-api-keys are ignored.
`private:true` is now handled and used in `AWS::ApiGateway::Method`.
> Added handling of 'private' param to http events.

- lib/yamlParser.js
- lib/yamlParser.test.js
Currently this plugin is setting the step function, state machine, and activity keys before the `serverless.yml` file has populated the variables.
This allows you to organize serverless.yml like such:
```
stepFunctions:
stateMachines:
${file(config/env/${opt:stage}.yml):stateMachines}
```
but _not_ like this
```
stepFunctions:
${file(config/env/${opt:stage}.yml):stepFunctions}
```
This proposed change populates the variables before determining whether or not a step function exists in the given config.
> Populating object before parsing step function

- README.md
- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
Implements support for customizing body mapping templates as discussed in https://github.com/horike37/serverless-step-functions/issues/92.
> Add support for custom body mapping templates

- README.md
- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
- lib/deploy/events/schedule/compileScheduledEvents.js
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/invoke/invoke.js
- lib/naming.js
- lib/naming.test.js
I think it would be better to just use the key as the logical id, but this is more backwards-compatible.
This allows specifying an id that is different than the name. This makes it more deterministic for purposes of Ref, etc.
```yml
stepFunctions:
stateMachines:
foo:
id: MyStateMachine # this only needs to be unique within the template
name: myStateMachine-${opt:stage} # this has to be unique across stages, etc.
```
In fact, where `key` means the stateMachines key for a given state machine, I think making the name default to "{service}-{key}-{stage}" and the logicalId to `{Key}StepFunctionStateMachine` is a very sensible default.
> Support custom logicalId separate from name

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/iam-role-statemachine-execution-template.txt
implements #134 
- renamed IAM role template to .txt so to avoid it getting automatically parsed as JSON (which then has to be JSON stringified)
- updated the IAM role template so that resource is templated
- collect function ARNs from state machines, and use them to set the resource of the IAM role
> Restrict permissions given to the generated IAM role

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- There is a bug with the resource field being empty reported here: https://github.com/horike37/serverless-step-functions/issues/146
- This is due to an issue with the regex not allowing numbers/* character which is common in function arn's.
- I refactored the regex to only allow valid characters for a function arn.
> Refactor function resource arn regex to only allow valid characters

- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.js
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.test.js
- lib/index.js
- lib/index.test.js
- lib/naming.js
This PR adds support for `cloudwatchEvent` events. For instance:
```
stepFunctions:
stateMachines:
first:
events:
- cloudwatchEvent:
event:
source:
- aws.ec2
detail-type:
- EC2 Instance State-change Notification
detail:
state:
- pending
definition:
...
```
> Add support for CloudWatch Events

- lib/deploy/events/apiGateway/deployment.js
- lib/deploy/events/apiGateway/deployment.test.js
The ServiceEndpoint output value for endpoints urls generated by the Serverless framework is being overwritten incorrectly by the serverless-step-functions plugin.
I've described the issue in detail here: https://github.com/horike37/serverless-step-functions/issues/149
This PR changes the ServiceEndpoint generation for API gateway deployments to match the output generated by Serverless framework.
> Service endpoint fix

- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
- based on #111
- thanks @alex-berger
I hope I have addressed all the remaining issues.
Cheers
>  Add support for CloudFormation intrinsic function for role

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
* Just adding $ as an allowed character in the function arn
* Various users are reporting this issue on https://github.com/horike37/serverless-step-functions/issues/146
> Add dollar sign to function arn regex

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/iam-role-statemachine-execution-template.txt
- refactored the compile IAM role module to make it easier to support future integrations
- generate appropriate roles for SNS, SQS, DynamoDB, ECS and Batch permissions to mirror the permissions that the AWS Console would generate when asked to create the roles
- consolidate permissions by common actions and then resources, to minimise number of policy statements
> Add support for other AWS services

- README.md
- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
Implement support for a `dependsOn` option on the state machine, as suggested in #158
> add support for dependsOn option

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
> fix generated IAM role when there are no Task states

- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.test.js
- lib/deploy/stepFunctions/compileIamRole.test.js
The way `validateConfig` works will generate some error logs when no alarms are defined at all.
After upgrading to the latest serverless-step-functions we got some logs about alarms but we don't have alarms defined. I think we should not have log about "alarms config is malformed" when no alarms are defined.
Following https://github.com/horike37/serverless-step-functions/pull/167
Sidenote: I've enable `sinon.spy()` instead of `console.log` in `compileIamRole.test.js` to avoid noisy log during tests. I can remove that if you don't agree.
> Avoid alarms logs when no alarms are defined

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
PR for #179 
Added glue IAM role logic and unit tests.
> Glue IAM role support

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
When using `ecs:runTask.sync` task, I have this error when trying to start the job:
> User: arn:aws:sts::01234567890:assumed-role/my-service-staging-IamRoleStateMachineExecut-HOBGIVKJHLN/gaegregerhbeahberg is not authorized to perform: iam:PassRole on resource: arn:aws:iam::01234567890:role/ecsTaskExecutionRole (Service: AmazonECS; Status Code: 400; Error Code: AccessDeniedException; Request ID: 37158697-a9c5-4ce8-8044-812c988dea0a)
The corresponding ASL template:
```
{
"StartAt": "RunTask",
"States": {
"RunTask": {
"Type": "Task",
"Resource": "arn:aws:states:::ecs:runTask.sync",
"Parameters": {
"Cluster": "my-service-staging-FargateTasksCluster-IGVGYRTYBHUN",
"TaskDefinition": "arn:aws:ecs:eu-west-1:01234567890:task-definition/my-task:8"
},
"End": true
}
}
}
```
The fix was to add …
> fix: adding 'iam:PassRole' permission for ECS

- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
1) body is object not string; 
2) ordering of props; 
3) queryStringParameters return {} instead of null; 
4) pathParameters return {} instead of null; 
5) stageVariables return {} instead of null;
6) no requestContext.domainName and requestContext.domainPrefix
cc/ @andrhamm
> fix: address some diffs with lambda_proxy

- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/utils/aws.js
When a state starts with "Ref" the state is interpreted as an intrinsic
function, this fix change the behaviour to look for "Ref" explicitly
instead of startsWith
Closes #203
> fix: match for Ref explicitly

- lib/deploy/events/apiGateway/deployment.js
- lib/deploy/events/apiGateway/deployment.test.js
> fix: fix incorrect ServiceEndpoint

- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.schema.js
Using Joi to define and validate the schema for the `alarms` configuration.
> refactor: use Joi schema to validate alarms schema

- lib/yamlParser.js
- lib/yamlParser.test.js
serverless 1.45.0 adds the ability to pass a `--config` option when deploying a stack so it doesn't always read from `serverless.yml`.  
I added some tests and a condition to yamlParser to check for this option if it has been passed.
> feat: reads config option to be compatible with serverless v1.45.0

- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/yamlParser.js
- package-lock.json
- package.json
Replaces #90
This PR adds pre-deployment definition validation using [asl-validator](https://www.npmjs.com/package/asl-validator). The latter [now supports intrinsic CF functions](https://github.com/airware/asl-validator/pull/35), which removes the need for serverless-pseudo-parameters support.
In contrast to #90 which adds a new command (`sls validate stepf`), here we automatically validate the state machine definitions during the deploy step. The main benefit is to avoid uploading and updating CloudFormation stack in order to detect and fix typos, so it can save some time when developing.
The feature is disabled by default, and can be enabled with a boolean:
```yaml
stepFunctions:
validate: true
```
I think this behaviour is better than the one in #90, but I'm happy to discuss it and …
> feat: asl validation

- README.md
Our serverless.yml files were getting a bit unwieldy with too many step functions so I thought this change might help slim them down by allowing us to extract each step function definition to a file.
This mimics the existing behaviour of the `resources:` section in serverless.yml
See: https://github.com/serverless/serverless/pull/2842
I've tested the code by deploying the step functions as in-line definitions and as external file and checking that there were no differences in the CloudFormation stack.
Let me know if there is anything else I need to do.
Thanks!
> docs: add example for separate files

- lib/deploy/events/apiGateway/methods.js
It seems in the `LAMBDA_PROXY_REQUEST_TEMPLATE`, all the variables `$context.authorizer.*` are omitted.
Looping on the `$context.authorizer.*` allow you to get back the data you pass in a policy generated by a custom authorizer.
Source : https://docs.aws.amazon.com/en_en/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html and https://docs.aws.amazon.com/en_en/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html
> feat: add all authorizer context properties to lambda_proxy template

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Should solve: #253 
I got an idea that maybe it would be nice if we could set QueueArn in State Machine definition like this:
```yaml
some-step:
Type: Task
Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
Parameters:
QueueUrl: { "Fn::ImportValue": "some-queue-url" }
QueueArn: { "Fn::ImportValue": "some-queue-arn" }
Message: "42"
End: true
```
But I wasn't sure how this would fit to architecture of whole project.
> Fix SQS QueueUrl transformation to ARN when intrinsic function being passed in

- README.md
Example YAML to launch a state machine using Map state.
> docs: add map state example

- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
> fix: intrinsics in array not detected

- README.md
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.js
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.test.js
This will add support to custom cloudwatch event buses or EventBridge. 
Two weeks ago, AWS [added support ](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eventbridge-supports-aws-cloudformation/?nc1=h_ls)to use custom `EventBusName` in `AWS::Events::Rule` resources : https://docs.aws.amazon.com/en_pv/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventbusname
> feat: support EventBusName for custom Cloudwatch event bus

- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
Applying the single quote fix from #235 to lambda proxy template
> Fix serialization errors in lambda_proxy template when using single quotes in payload

- lib/yamlParser.js
- lib/yamlParser.test.js
The plugin does not currently work if you try to use a custom config file that is in another folder.  This PR attempts to fix that.
```
$ sls deploy --config ./services/myfile.yml
Error --------------------------------------------------
Error: ENOENT: no such file or directory, open '/mypath/myfile.yml'
at Object.fs.openSync (fs.js:646:18)
at Object.fs.readFileSync (fs.js:551:33)
at readFileSync (/Users/me/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/utils/fs/readFileSync.js:7:24)
at Utils.readFileSync (/Users/me/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/Utils.js:84:12)
at YamlParser.parse (/Users/me/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/YamlParser.js:17:40)
at ServerlessStepFunctions.yamlParse …
```
> support relative config filename

- lib/deploy/events/apiGateway/methods.js
It seems like #254 broke the lambda proxy template by introducing an extra comma at the end of a loop, causing an invalid json structure.
This is a simple fix - moving the loop so it's not the end of the json structure
> fix invalid lambda_proxy template

- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.schema.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
Global tags become optional for inheriting
fixes #287
> fix: #287 don't include Tags property if no tags provided

- lib/yamlParser.js
- lib/yamlParser.test.js
This PR builds upon what was started in PR #159 and adds tests
Fixes: #292
> feat: support loading config from JS and JSON files

- README.md
- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
> feat: support response headers and template

- lib/deploy/events/apiGateway/methods.js
- lib/deploy/events/apiGateway/methods.test.js
This PR fixes bug #307.  I have tested in a live AWS environment that this solves the bug, and I have ran/updated tests.
@theburningmonk @horike37 Please let me know if this is suitable for merging into master.  
Thanks.
> fix: partition parsing of apigateway arn for events in govcloud region

- README.md
This is a pull request which fixes README only.
#156 added support for CloudFormation intrinsic function for role, such as `Ref` or `Fn::GetAtt`. The function should return the role's ARN, not its name.
The example in README `Ref: StateMachineRole` doesn't work because that returns the role's name. Instead, we should use `Fn::GetAtt`.
> fix(README): should specify the role's ARN

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
Currently, logging is available only for express workflows. this pull request enables it for standard workflows as well
> Allow logging to standard workflow

- README.md
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.js
Possible fix for this issue https://github.com/serverless-operations/serverless-step-functions/issues/306 It allows to add already created role to CloudWatch event
> Add custom role to cloudwatch event which trigger step functions

- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
- lib/yamlParser.js
This option suppresses output to the Outputs section of Cloudformation.
https://dev.classmethod.jp/articles/serverless-framework-stepfunctions-many-statemachine-workaround/
> feat: not output cloudformation outputs section

- lib/deploy/stepFunctions/compileIamRole.js
Hello 👋
Today I had a typo in my configuration, I wrote "definitions" instead of "definition"...
Serverless was telling me "TypeError: Cannot read property 'States' of undefined" after some time when deploying.
Without opening the code I couldn't understand what happend. Thus I added this error to help end user to debug faster :)
> Trigger error when 'definition' is missing

- README.md
Noticed the example was missing the `stateMachines:` key when defining multiple file state machines. 
Thanks a lot for the plugin, it's really great!
> updates readme to fix multifile state machines

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Here are the changes I am proposing in response to https://github.com/serverless-operations/serverless-step-functions/issues/329
> feat: add functionality for variable FunctionName in lambda state

- lib/deploy/events/apiGateway/methods.js
Make requestTimeEpoch value a number in the default lambda_proxy mapping template. "requestTimeEpoch" is handled as a number in the AWS SDK for typed languages and causes parsing issues when using a typed language such as c#.
> Lambda_proxy mapping template fix

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Hi,
I added a support for IAM Role generation when using `arn:aws:states:::states:startExecution.sync:2`. As [AWS documentation](https://docs.aws.amazon.com/step-functions/latest/dg/connect-stepfunctions.html) describe
the `:2` version can be used to have JSON output of nested step function instead of encoded string.
> Add IAM Role generation support for resource "startExecution.sync:2"

- lib/yamlParser.js
- lib/yamlParser.test.js
addresses: https://github.com/serverless-operations/serverless-step-functions/issues/349
serverless now supports typescript: https://github.com/serverless/serverless/pull/7755
updating this plugin to look for `.ts` files
> feat(ts-support): adds ts support

- README.md
- lib/deploy/stepFunctions/compileStateMachines.js
- lib/deploy/stepFunctions/compileStateMachines.schema.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
add ability to set DeletionPolicy to Retain for State Machine
> feat: retain config

- .travis.yml
deprecate node8 tests since it's no longer supported on Lambda
> ci: updated .travis.yml

- lib/index.js
For now I have added only the most basic validation for the top level structure to silence the warning and allow people to use the stricter schema validation.
Closes: #355
> Add basic schema validation

- README.md
I also tried to tidy up some of the text a bit (the second commit).
> Fix typo in example code in readme

- lib/deploy/events/apiGateway/authorizers.js
- lib/deploy/events/apiGateway/authorizers.test.js
- lib/index.js
- package.json
Removed the Dependency on the serverless library resolving issue #368 
It's pretty much copied from the library which seems wrong, but the rest of the deploy/events/apiGateway code are pretty much the same.
> feat: moved authorizers out into code

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
#373 
It generates IAM permission for StateMachine to use X-Ray when enabled tracingConfig.
(Should I rename commit type 'feat' to 'fix'?)
> fix: added iam permission for x-ray

- README.md
- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.schema.js
- lib/deploy/stepFunctions/compileAlarms.test.js
- package.json
Fixes https://github.com/serverless-operations/serverless-step-functions/issues/376
> feat: add ExecutionSucceeded as a valid metric

- lib/deploy/stepFunctions/compileAlarms.schema.js
The same as #263 but for alarm topics.
```
alarms:
topics:
ok:
Fn::ImportValue: my-alarm-topic
alarm:
Fn::ImportValue: my-alarm-topic
metrics:
- executionsTimedOut
- executionsFailed
- executionsAborted
```
> feat: allow Fn::ImportValue for alarm topics

- lib/deploy/stepFunctions/compileAlarms.schema.js
- lib/deploy/stepFunctions/compileNotifications.schema.js
- lib/deploy/stepFunctions/compileStateMachines.schema.js
Hi there!
I found myself wanting to be able to use the `Fn::Join` CloudFormation pseudo parameter function and noticed that it was being rejected by validation. After adding it to the ARN deploy schemas, it seems to work fine - resources are created as expected.
I have only tested alarms and notifications, however I added it to the state machines schema as well for consistency.
What do you think about allowing `Fn::Join` to the validation schemas? I'm more than happy to make any changes you'd like to the code.
Cheers, and thank you for the useful plugin!
> feat: added Fn::Join to ARN deployment schemas

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Implements support for sagemaker createTransformJob.sync and resolves https://github.com/serverless-operations/serverless-step-functions/issues/385
> feat: add IAM Role support for createTransformJob.sync

- lib/index.js
Fixes deprecation `CLI_OPTIONS_SCHEMA` documented here: https://www.serverless.com/framework/docs/deprecations/
```text
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
- ServerlessStepFunctions for "name", "data", "path", "stage", "region"
Please report this issue in plugin issue tracker.
Starting with next major release, this will be communicated with a thrown error.
More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
```
Fixes #415
> fix: add required type parameter to cli options

- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.js
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.test.js
Resolves #405 by using JSON.stringify so that [object, object] is not the out put of the Cloudformation template.
> bug(eventbus): stringify eventbus name

- lib/deploy/events/apiGateway/apiKeys.js
- lib/deploy/events/apiGateway/apiKeys.test.js
- lib/deploy/events/apiGateway/restApi.js
- lib/deploy/events/apiGateway/restApi.test.js
- lib/deploy/events/apiGateway/usagePlan.js
- lib/deploy/events/apiGateway/usagePlan.test.js
- lib/deploy/events/apiGateway/usagePlanKeys.js
- lib/deploy/events/apiGateway/usagePlanKeys.test.js
In the context of Serverless Framework, API Gateway specific properties as `apiKeys`, `resourcePolicy`, `usagePlan` were moved from `provider` context to `provider.apiGateway` context.
There's no plan to support old notation with a new major release of the Framework.
This PR ensures that the plugin will remain working without issues in v3 of the Framework
/cc @horike37
> Regognize API Gateway properties at `provider.apiGateway`

- README.md
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.js
- lib/deploy/events/cloudWatchEvent/compileCloudWatchEventEvents.test.js
Hey, I created this PR regarding issue #463
> Support configure DLQ on EventBridge Targets

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/utils/arm.test.js
- lib/utils/arn.js
- lib/utils/aws.js
- lib/utils/aws.test.js
This adds AWS Gov Cloud support (and possibly China support) by replacing the generic "aws" reference to the `{ Ref: "Partition" }` CloudFormation psuedo-parameter.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition
> Replace "aws" with parititon ref

- README.md
Hi, the current **Specify Input or Inputpath** inline link is not working.
> docs: fix Inline Link in README.md

- README.md
- lib/deploy/stepFunctions/compileAlarms.js
- lib/deploy/stepFunctions/compileAlarms.schema.js
- lib/deploy/stepFunctions/compileAlarms.test.js
This PR adds support for custom alarm names, currently, all alarms created enabled by the serverless step functions plugins do not set the CloudFormation property `AlarmName`.
This PR enables 2 ways to change the alarm name.
- name template
- per-metric alarm name
```yaml
service: myservice
plugins:
- serverless-step-functions
stepFunctions:
stateMachines:
main-workflow:
name: main
alarms:
nameTemplate: $[stateMachineName]-$[cloudWatchMetricName]-alarm
topics:
alarm: !Ref AwsAlertsGenericAlarmTopicAlarm
metrics:
- executionsFailed
- executionsAborted
- executionsTimedOut
- executionThrottled
treatMissingData: ignore
definition: ${file(./step-functions/main.asl.yaml)}
```
With the `nameTemplate` property the user has the flexibility to change the alarm name, based on this plugin: …
> feat(alarm): support for custom alarm names

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Creates the IAM Role for tasks which are to fetch an object and return it's content, for example:
```yaml
FetchExecutionConfiguration:
Type: Task
Resource: arn:aws:states:::aws-sdk:s3:getObject
Next: DoSomeThingWithConfiguration
Parameters:
Bucket: "my-execution-configs"
Key: "config.json"
```
Currently a task defined this way will result in the following error.
> Cannot generate IAM policy statement for Task state
With this change it correctly deploys and runs, with only the minimum permission granted (i.e. `s3:GetObject` on the specified file).
See:
[Supported AWS SDK service integrations](https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html#supported-services-awssdk-list)
Note: This is the fixed version of pull request #507
> feat: add support for having a task be based on an object in S3

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Adds support for Redshift Data.
It makes it possible to create state machines that directly use Redshift Data to run statements on clusters with temporary credentials and then fetch the results.
> feat: add support for Redshift Data

- lib/yamlParser.js
We use serverless-import-config-plugin, but this plugin will only use config in the main serverless.yml entry file.
This PR fixes that and sets the defaults in a simpler way
> fix: Make it work with serverless-import-config-plugin

- package-lock.json
- package.json
The old `asl-validator` doesn't support `aws-us-gov` (or, for that matter, anything other than just `aws`) as a partition when specifying the `Resource:` property in step functions
That makes it impossible to use this plugin with AWS GovCloud :(
Fortunately, upgrading the dependency to its latest version solves the issue!
> feature: update asl-validator to v3

- lib/deploy/events/schedule/compileScheduledEvents.js
- lib/deploy/events/schedule/compileScheduledEvents.test.js
- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/deploy/stepFunctions/compileNotifications.test.js
This PR allows using a Permissions Boundary defined in the provider level e.g. 
``` yaml
provider:
name: aws
runtime: python3.9
rolePermissionsBoundary: arn:aws:iam::[account]:policy/permission_boundary  
```
Previously, the boundary was only applied to the created lambda execution role, but was missing on the created roles for functions of the state machine as described in [issue 395](https://github.com/serverless-operations/serverless-step-functions/issues/395) some time ago. 
We run into the same issue yesterday well using the newest version of serverless and this plugin. The submitted fix worked for us.
> fix(permissionsBoundary): apply permissionsBoundary

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
When building a new step function I noticed that what was previously the `Iterator` has been changed to `ItemProcessor`. Probably changed with reinvent and their release of Distributed Maps. Here's an example of a state machine that I built with their visual builder and then adjusted to reference my functions: https://github.com/bahrmichael/trade-game-backend/pull/50/commits/9a75d378d7e67673bffc448f5507793c2eb9408e#diff-ea2dbe8c0992878214f1020b0c7ee79668dc63b5c8325a5ed67892d0080a9b27
When setting `validate: true` I noticed that the plugin expects an `Iterator` within a `Map` task, which fails with the new `ItemProcessor`: https://github.com/bahrmichael/trade-game-backend/actions/runs/3633513042/jobs/6130610217
This PR shows how far I've gotten, but there seems to be another error where …
> feat: support the latest SFN ItemProcessor (replaces Iterator)

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
**Issue**: When `ItemReader` is used to download the files from S3, IAM policy is not created to access S3.
**Solution**: Adding an IAM policy with `Resource: *` when the bucket and key are sent dynamically.
`Resource: *`: [ItemReader AWS Documenation](https://docs.amazonaws.cn/en_us/step-functions/latest/dg/input-output-itemreader.html#itemreader-iam-policiesac)
**Notes**: I cross referenced the policy by  creating step function from AWS UI and the IAM policy generated had `Resource: *` when `bucket` and `key` were passed dynamically.
Please let me know if I need to make any further changes.
> feat: generate IAM policy for S3 when ItemReader is used

- package-lock.json
- package.json
New version of `asl-validator` is published yesterday https://www.npmjs.com/package/asl-validator
We could potentially update some of new MAP features that were added to the validator.
> feat: update asl_validator plugin

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
**Issue**: When executing a state machine with a [Map state in Distributed mode](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-distributed.html), the execution fails at the Map state because execution role does not have sufficient permissions to run a Distributed Map.
**Solution**: I tired to use the current pass that we do to collect the tasks and generate additional policy which gives access to trigger the `stepFunction`. I couldn't find a better way to access the name of the `stepFunction` so I had to pass it as a parameter.
This should also solve this [issue](https://github.com/serverless-operations/serverless-step-functions/issues/543)
**Notes:**
- With the changes in the PR, I've deployed my stepFunction to AWS and it seems to work alright in …
> feat: add IAM role to distributed_map to start the state machine

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
This PR adds support to generate IAM statements for `dynamodb:Query`.
Currently I get this error:
```
Cannot generate IAM policy statement for Task state { Type: 'Task',
Parameters:
{ TableName: { Ref: 'OrdersTable' },
IndexName: 'GSI1',
KeyConditionExpression: 'gsi1 = :k',
FilterExpression: '$.listMatchableOrdersFilter',
ExpressionAttributeValues: { ':k': { 'S.$': '$.listMatchableOrdersKey' }, ':p': { 'N.$': '$.newOrder.pricePerUnit' } } },
Resource: 'arn:aws:states:::aws-sdk:dynamodb:query',
Next: 'Is Empty?',
ResultPath: '$.matchableOrders' }
```
With this PR it should be able to generate a statement that supports the Query operation, and also supports GSIs. I went with a wildcard `*` index following the table related code above. If the index name is only known at runtime, there's no …
> feat: generate permission for dynamodb:Query and for GSIs

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Fixes #543 by looking for a 'name' field on the state machine and falling back to using it's ID if no name is provided.
> feat: support custom state machine names when using a distributed mapA

- lib/index.js
- lib/index.test.js
`<pedantry>`Change `OutPuts` to `Outputs``</pedantry>` 😳
> Remove accidental camel case in message

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
This PR involves 3 related tasks:
1. Compile IAM roles for ResultWriter in Map states
2. Compile IAM roles for steps using s3:PutObject as required for ResultWriter, and also for SDK integrations
3. Fix an incorrect test expectation for s3 IAM roles
- specifying a non-path value for path parameters like `Bucket.$` is not valid ASL syntax
Example steps:
```
Store-In-S3:
Type: Task
Resource: arn:aws:states:::aws-sdk:s3:putObject
Parameters:
Bucket: bucket-name
Key: key.json
Body.$: $
```
```
S3-Output:
Type: Map
MaxConcurrency: 1
End: true
ItemProcessor:
ProcessorConfig:
Mode: DISTRIBUTED
ExecutionType: EXPRESS
StartAt: Inner-Step
States:
Inner-Step:
Type: Pass
End: true
ResultWriter:
Resource: arn:aws:states:::s3:putObject
Parameters:
Bucket: bucket-name
Prefix: s3-output-map-result
```
> Support s3 putobject task

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Creates the IAM Role for tasks which use the batch tasks targeting one or more dynamoDB tables. Supports BatchWriteItem and BatchGetItem
Currently a task defined this way will result in the following error.
`Cannot generate IAM policy statement for Task state`
With this change it correctly deploys and runs with permissions created for the minimal set of tables if possible.
RequestItems may specify the table names as keys, in which case permission resources will be applied only to the tables listed e.g.
```
WriteBatchToDynamo:
Type: Task
Resource: arn:aws:states:::aws-sdk:dynamodb:batchWriteItem
Parameters:
RequestItems:
usersTable: $.userRequests
postsTable: $.postRequests
ReturnConsumedCapacity: TOTAL
ResultPath: $.writeResult
End: true
```
RequestItems can also be specified fully at …
> feat: add support dynamoDB batch tasks using AWS SDK service integration

- lib/deploy/events/schedule/compileScheduledEvents.js
- lib/deploy/events/schedule/compileScheduledEvents.test.js
- lib/naming.js
> Create Schedules using Eventbridge Scheduler

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Expands support for Redshift Data.
It adds support for running statements on Redshift Serverless workgroups as well as using Secrets Manager secrets or IAM identities for authentication.
> feat: expand support for Redshift Data

- lib/deploy/events/schedule/compileScheduledEvents.js
- lib/deploy/events/schedule/compileScheduledEvents.test.js
Simple change to fix https://github.com/serverless-operations/serverless-step-functions/issues/571#issuecomment-1753443231
More info in that comment.
> feat(EventBridge Scheduler): Enable passing input to target

- README.md
The functionality of EventBridge Scheduler has been added to solve the issue #571, and the method to utilize this functionality has been documented.
> docs: update README with EventBridge Scheduler

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Implements IAM Role support for bedrock invokeModel with foundation models ([IAM Role Documentation](https://docs.aws.amazon.com/step-functions/latest/dg/bedrock-iam.html#bedrock-policy-invoke-foundation-model)).
Note: `ModelId` can be specified as an ARN or [a valid model ID](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) ([InvokeModel Documentation](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html)).
> feat: add IAM Role support for bedrock invokeModel with foundation models

- package-lock.json
- package.json
Closes #614 
Upgraded serverless peer dependency to allow versions starting from 2.32.0 (equal to and/or greater than).
1) When I ran `npm install`, I got the warning that this lock-file was made with an older version of npm. According to the CLI logs, some "supplemental" metadata was fetched from the registry.  
My system currently runs **node v20.14.0 (LTS)** and **npm v10.7.0**  
2) All tests succeeded after this change.
> chore: :arrow_up: upgrade serverless peer dependency

- .github/workflows/config.yml
Update Node.js version from 14 to 18 in GitHub Actions to resolve compatibility issues with the `Object.hasOwn` method.
- Update the libraries in use
- Update Node.js version from 14 to 18
- Modified npm install command to use `--legacy-peer-deps` flag
The following error occurs when running tests in the current CI environment:
```
1) #compileStateMachines
should validate definition and pass:
TypeError: Object.hasOwn is not a function
at new JSONPath (node_modules/jsonpath-plus/dist/index-node-cjs.cjs:1530:22)
at JSONPath (node_modules/jsonpath-plus/dist/index-node-cjs.cjs:1509:14)
at missingTransitionTargetErrors (node_modules/asl-validator/dist/src/checks/missing-transition-target-errors.js:9:34)
at validator (node_modules/asl-validator/dist/src/validator.js:35:104)
at …
```
> Updating the CI environment

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
- lib/deploy/stepFunctions/compileStateMachines.test.js
AWS recently introduced support for JSONata expressions as an alternative to JSONPath:
https://aws.amazon.com/blogs/compute/simplifying-developer-experience-with-variables-and-jsonata-in-aws-step-functions/
https://docs.aws.amazon.com/step-functions/latest/dg/transforming-data.html
This PR adds support for new fields to use JSONata expressions.
> feat: support JSONata query language

- package-lock.json
- package.json
This bumps asl-validator to version 3.11.0. This should address the [RCE vulnerability in JSONPath Plus](https://github.com/advisories/GHSA-pppg-cpfq-h7wr). This has already been addressed in the [asl-validator](https://github.com/ChristopheBougere/asl-validator/pull/164) dependency, which depends on jsonpath-plus.
> chore: bump asl-validator to 3.11.0

- .github/workflows/config.yml
Update CI workflow to use latest ubuntu image since ubuntu-20.04 is deprecated:
https://github.com/actions/runner-images/issues/11101
> chore(deps): update ubuntu image 

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
When using JSONata as the query language, AWS creates the step definition with `Arguments` instead of `Parameters`.
Example:
```diff
Step name:
Type: Task
Resource: arn:aws:states:::lambda:invoke
Output: '{% $states.result.Payload %}'
- Parameters:
+ Arguments:
FunctionName: <function ARN goes here>
Payload: '{% $states.input %}'
```
That leads to the error below
```txt
Deploying "project-name" to stage "staging" (us-east-1)
Layer sharp is already uploaded.
✖ Stack staging-project-name failed to deploy (7s)
✖ TypeError: Cannot read properties of undefined (reading 'FunctionName')
at ServerlessStepFunctions.getLambdaPermissions (/home/edvaldo/project-name/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:365:41)
at …
```
> feat: support `Arguments` for Lambda when query language is JSONata

- .github/workflows/config.yml
- package-lock.json
- package.json
Update Node.js version from 18 to 20 in GitHub Actions and set an `engines` node Node version in the `package.json` file. 
[AWS currently supports ](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported)the following Node.js versions:
- Node.js v22.x (until April 30, 2027)
- Node.js v20.x (until April 30, 2026)
- **Node.js v18.x (until September 1, 2025)**
> chore: update Node to v20

- lib/deploy/stepFunctions/compileIamRole.js
- lib/deploy/stepFunctions/compileIamRole.test.js
Resolves #647
Note: I'll add unit tests if the proposed solution in this PR is correct. This solution works for me, but I wasn't sure if there was a better way to fix this issue.
> fix: added support for generating S3 permissions using Bucket references
